// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

final _JvmClassMappingKtClass =
    jni$_.JClass.forName(r'kotlin/jvm/JvmClassMappingKt');

final _id_getJavaClass = _JvmClassMappingKtClass.staticMethodId(
  r'getJavaClass',
  r'(Lkotlin/reflect/KClass;)Ljava/lang/Class;',
);

final _getJavaClass = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final java.lang.Class<T> getJavaClass(kotlin.reflect.KClass<T> kClass)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getJavaClass<$T extends jni$_.JObject?>(
  jni$_.JObject kClass, {
  required jni$_.JObjType<$T> T,
}) {
  final _$kClass = kClass.reference;
  return _getJavaClass(_JvmClassMappingKtClass.reference.pointer,
          _id_getJavaClass as jni$_.JMethodIDPtr, _$kClass.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}

final _id_getJavaPrimitiveType = _JvmClassMappingKtClass.staticMethodId(
  r'getJavaPrimitiveType',
  r'(Lkotlin/reflect/KClass;)Ljava/lang/Class;',
);

final _getJavaPrimitiveType = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final java.lang.Class<T> getJavaPrimitiveType(kotlin.reflect.KClass<T> kClass)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject? getJavaPrimitiveType<$T extends jni$_.JObject?>(
  jni$_.JObject kClass, {
  required jni$_.JObjType<$T> T,
}) {
  final _$kClass = kClass.reference;
  return _getJavaPrimitiveType(_JvmClassMappingKtClass.reference.pointer,
          _id_getJavaPrimitiveType as jni$_.JMethodIDPtr, _$kClass.pointer)
      .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
}

final _id_getJavaObjectType = _JvmClassMappingKtClass.staticMethodId(
  r'getJavaObjectType',
  r'(Lkotlin/reflect/KClass;)Ljava/lang/Class;',
);

final _getJavaObjectType = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final java.lang.Class<T> getJavaObjectType(kotlin.reflect.KClass<T> kClass)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getJavaObjectType<$T extends jni$_.JObject?>(
  jni$_.JObject kClass, {
  required jni$_.JObjType<$T> T,
}) {
  final _$kClass = kClass.reference;
  return _getJavaObjectType(_JvmClassMappingKtClass.reference.pointer,
          _id_getJavaObjectType as jni$_.JMethodIDPtr, _$kClass.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}

final _id_getKotlinClass = _JvmClassMappingKtClass.staticMethodId(
  r'getKotlinClass',
  r'(Ljava/lang/Class;)Lkotlin/reflect/KClass;',
);

final _getKotlinClass = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final kotlin.reflect.KClass<T> getKotlinClass(java.lang.Class<T> class)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getKotlinClass<$T extends jni$_.JObject?>(
  jni$_.JObject class$, {
  required jni$_.JObjType<$T> T,
}) {
  final _$class$ = class$.reference;
  return _getKotlinClass(_JvmClassMappingKtClass.reference.pointer,
          _id_getKotlinClass as jni$_.JMethodIDPtr, _$class$.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}

final _id_getJavaClass$1 = _JvmClassMappingKtClass.staticMethodId(
  r'getJavaClass',
  r'(Ljava/lang/Object;)Ljava/lang/Class;',
);

final _getJavaClass$1 = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final java.lang.Class<T> getJavaClass(T object)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getJavaClass$1<$T extends jni$_.JObject?>(
  $T object, {
  required jni$_.JObjType<$T> T,
}) {
  final _$object = object?.reference ?? jni$_.jNullReference;
  return _getJavaClass$1(_JvmClassMappingKtClass.reference.pointer,
          _id_getJavaClass$1 as jni$_.JMethodIDPtr, _$object.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}

final _id_getRuntimeClassOfKClassInstance =
    _JvmClassMappingKtClass.staticMethodId(
  r'getRuntimeClassOfKClassInstance',
  r'(Lkotlin/reflect/KClass;)Ljava/lang/Class;',
);

final _getRuntimeClassOfKClassInstance = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final java.lang.Class<kotlin.reflect.KClass<T>> getRuntimeClassOfKClassInstance(kotlin.reflect.KClass<T> kClass)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getRuntimeClassOfKClassInstance<$T extends jni$_.JObject?>(
  jni$_.JObject kClass, {
  required jni$_.JObjType<$T> T,
}) {
  final _$kClass = kClass.reference;
  return _getRuntimeClassOfKClassInstance(
          _JvmClassMappingKtClass.reference.pointer,
          _id_getRuntimeClassOfKClassInstance as jni$_.JMethodIDPtr,
          _$kClass.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}

final _id_isArrayOf = _JvmClassMappingKtClass.staticMethodId(
  r'isArrayOf',
  r'([Ljava/lang/Object;)Z',
);

final _isArrayOf = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticBooleanMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `synthetic static public final boolean isArrayOf(java.lang.Object[] objects)`
bool isArrayOf(
  jni$_.JArray<jni$_.JObject?>? objects,
) {
  final _$objects = objects?.reference ?? jni$_.jNullReference;
  return _isArrayOf(_JvmClassMappingKtClass.reference.pointer,
          _id_isArrayOf as jni$_.JMethodIDPtr, _$objects.pointer)
      .boolean;
}

final _id_getAnnotationClass = _JvmClassMappingKtClass.staticMethodId(
  r'getAnnotationClass',
  r'(Ljava/lang/annotation/Annotation;)Lkotlin/reflect/KClass;',
);

final _getAnnotationClass = jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
                jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                    jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
        'globalEnv_CallStaticObjectMethod')
    .asFunction<
        jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr,
            jni$_.Pointer<jni$_.Void>)>();

/// from: `static public final kotlin.reflect.KClass<? extends T> getAnnotationClass(T annotation)`
/// The returned object must be released after use, by calling the [release] method.
jni$_.JObject getAnnotationClass<$T extends jni$_.JObject?>(
  $T annotation, {
  required jni$_.JObjType<$T> T,
}) {
  final _$annotation = annotation?.reference ?? jni$_.jNullReference;
  return _getAnnotationClass(_JvmClassMappingKtClass.reference.pointer,
          _id_getAnnotationClass as jni$_.JMethodIDPtr, _$annotation.pointer)
      .object<jni$_.JObject>(const jni$_.JObjectType());
}
