name: blood_pressure_app
description: "A blood pressure tracker"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path_provider: ^2.1.3
  flutter_datetime_picker_plus: ^2.2.0
  d_chart: ^2.6.9
  cross_file: ^0.3.3+8
  csv: ^6.0.0

  intl: any
  signals: ^6.0.2
  file_picker: ^8.3.5
  signals_flutter: ^6.0.2
  shared_preferences: ^2.5.2
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
