name: blood_pressure_app
description: "A blood pressure tracker"

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  hive: ^2.2.3
  hive_generator: ^2.0.1
  path_provider: ^2.1.3
  numberpicker: ^2.1.2
  flutter_datetime_picker_plus: ^2.2.0
  d_chart: ^2.6.9
  excel: ^4.0.3
  file_picker: ^8.0.0+1
  cross_file: ^0.3.3+8

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
