// AUTO GENERATED BY JNIGEN 0.14.2. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' show Object, String, bool, double, int;
import 'dart:core' as core$_;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

import '../../android/content/Intent.dart' as intent$_;

import 'result/ActivityResultCallback.dart' as activityresultcallback$_;

import 'result/ActivityResultLauncher.dart' as activityresultlauncher$_;

/// from: `androidx.activity.ComponentActivity`
class ComponentActivity extends jni$_.JObject {
  @jni$_.internal
  @core$_.override
  final jni$_.JObjType<ComponentActivity> $type;

  @jni$_.internal
  ComponentActivity.fromReference(
    jni$_.JReference reference,
  )   : $type = type,
        super.fromReference(reference);

  static final _class =
      jni$_.JClass.forName(r'androidx/activity/ComponentActivity');

  /// The type which includes information such as the signature of this class.
  static const nullableType = $ComponentActivity$NullableType();
  static const type = $ComponentActivity$Type();
  static final _id_new$ = _class.constructorId(
    r'()V',
  );

  static final _new$ = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void <init>()`
  /// The returned object must be released after use, by calling the [release] method.
  factory ComponentActivity() {
    return ComponentActivity.fromReference(
        _new$(_class.reference.pointer, _id_new$ as jni$_.JMethodIDPtr)
            .reference);
  }

  static final _id_new$1 = _class.constructorId(
    r'(I)V',
  );

  static final _new$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_NewObject')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public void <init>(int i)`
  /// The returned object must be released after use, by calling the [release] method.
  factory ComponentActivity.new$1(
    int i,
  ) {
    return ComponentActivity.fromReference(
        _new$1(_class.reference.pointer, _id_new$1 as jni$_.JMethodIDPtr, i)
            .reference);
  }

  static final _id_onRetainNonConfigurationInstance = _class.instanceMethodId(
    r'onRetainNonConfigurationInstance',
    r'()Ljava/lang/Object;',
  );

  static final _onRetainNonConfigurationInstance =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public final java.lang.Object onRetainNonConfigurationInstance()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? onRetainNonConfigurationInstance() {
    return _onRetainNonConfigurationInstance(reference.pointer,
            _id_onRetainNonConfigurationInstance as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_onRetainCustomNonConfigurationInstance =
      _class.instanceMethodId(
    r'onRetainCustomNonConfigurationInstance',
    r'()Ljava/lang/Object;',
  );

  static final _onRetainCustomNonConfigurationInstance =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public java.lang.Object onRetainCustomNonConfigurationInstance()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? onRetainCustomNonConfigurationInstance() {
    return _onRetainCustomNonConfigurationInstance(reference.pointer,
            _id_onRetainCustomNonConfigurationInstance as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_getLastCustomNonConfigurationInstance =
      _class.instanceMethodId(
    r'getLastCustomNonConfigurationInstance',
    r'()Ljava/lang/Object;',
  );

  static final _getLastCustomNonConfigurationInstance =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public java.lang.Object getLastCustomNonConfigurationInstance()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? getLastCustomNonConfigurationInstance() {
    return _getLastCustomNonConfigurationInstance(reference.pointer,
            _id_getLastCustomNonConfigurationInstance as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_setContentView = _class.instanceMethodId(
    r'setContentView',
    r'(I)V',
  );

  static final _setContentView = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public void setContentView(int i)`
  void setContentView(
    int i,
  ) {
    _setContentView(
            reference.pointer, _id_setContentView as jni$_.JMethodIDPtr, i)
        .check();
  }

  static final _id_setContentView$1 = _class.instanceMethodId(
    r'setContentView',
    r'(Landroid/view/View;)V',
  );

  static final _setContentView$1 = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void setContentView(android.view.View view)`
  void setContentView$1(
    jni$_.JObject? view,
  ) {
    final _$view = view?.reference ?? jni$_.jNullReference;
    _setContentView$1(reference.pointer,
            _id_setContentView$1 as jni$_.JMethodIDPtr, _$view.pointer)
        .check();
  }

  static final _id_setContentView$2 = _class.instanceMethodId(
    r'setContentView',
    r'(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V',
  );

  static final _setContentView$2 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void setContentView(android.view.View view, android.view.ViewGroup$LayoutParams layoutParams)`
  void setContentView$2(
    jni$_.JObject? view,
    jni$_.JObject? layoutParams,
  ) {
    final _$view = view?.reference ?? jni$_.jNullReference;
    final _$layoutParams = layoutParams?.reference ?? jni$_.jNullReference;
    _setContentView$2(
            reference.pointer,
            _id_setContentView$2 as jni$_.JMethodIDPtr,
            _$view.pointer,
            _$layoutParams.pointer)
        .check();
  }

  static final _id_addContentView = _class.instanceMethodId(
    r'addContentView',
    r'(Landroid/view/View;Landroid/view/ViewGroup$LayoutParams;)V',
  );

  static final _addContentView = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void addContentView(android.view.View view, android.view.ViewGroup$LayoutParams layoutParams)`
  void addContentView(
    jni$_.JObject? view,
    jni$_.JObject? layoutParams,
  ) {
    final _$view = view?.reference ?? jni$_.jNullReference;
    final _$layoutParams = layoutParams?.reference ?? jni$_.jNullReference;
    _addContentView(reference.pointer, _id_addContentView as jni$_.JMethodIDPtr,
            _$view.pointer, _$layoutParams.pointer)
        .check();
  }

  static final _id_initializeViewTreeOwners = _class.instanceMethodId(
    r'initializeViewTreeOwners',
    r'()V',
  );

  static final _initializeViewTreeOwners = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void initializeViewTreeOwners()`
  void initializeViewTreeOwners() {
    _initializeViewTreeOwners(reference.pointer,
            _id_initializeViewTreeOwners as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_peekAvailableContext = _class.instanceMethodId(
    r'peekAvailableContext',
    r'()Landroid/content/Context;',
  );

  static final _peekAvailableContext = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public android.content.Context peekAvailableContext()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject? peekAvailableContext() {
    return _peekAvailableContext(
            reference.pointer, _id_peekAvailableContext as jni$_.JMethodIDPtr)
        .object<jni$_.JObject?>(const jni$_.JObjectNullableType());
  }

  static final _id_addOnContextAvailableListener = _class.instanceMethodId(
    r'addOnContextAvailableListener',
    r'(Landroidx/activity/contextaware/OnContextAvailableListener;)V',
  );

  static final _addOnContextAvailableListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnContextAvailableListener(androidx.activity.contextaware.OnContextAvailableListener onContextAvailableListener)`
  void addOnContextAvailableListener(
    jni$_.JObject onContextAvailableListener,
  ) {
    final _$onContextAvailableListener = onContextAvailableListener.reference;
    _addOnContextAvailableListener(
            reference.pointer,
            _id_addOnContextAvailableListener as jni$_.JMethodIDPtr,
            _$onContextAvailableListener.pointer)
        .check();
  }

  static final _id_removeOnContextAvailableListener = _class.instanceMethodId(
    r'removeOnContextAvailableListener',
    r'(Landroidx/activity/contextaware/OnContextAvailableListener;)V',
  );

  static final _removeOnContextAvailableListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnContextAvailableListener(androidx.activity.contextaware.OnContextAvailableListener onContextAvailableListener)`
  void removeOnContextAvailableListener(
    jni$_.JObject onContextAvailableListener,
  ) {
    final _$onContextAvailableListener = onContextAvailableListener.reference;
    _removeOnContextAvailableListener(
            reference.pointer,
            _id_removeOnContextAvailableListener as jni$_.JMethodIDPtr,
            _$onContextAvailableListener.pointer)
        .check();
  }

  static final _id_onPreparePanel = _class.instanceMethodId(
    r'onPreparePanel',
    r'(ILandroid/view/View;Landroid/view/Menu;)Z',
  );

  static final _onPreparePanel = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              int,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean onPreparePanel(int i, android.view.View view, android.view.Menu menu)`
  bool onPreparePanel(
    int i,
    jni$_.JObject? view,
    jni$_.JObject menu,
  ) {
    final _$view = view?.reference ?? jni$_.jNullReference;
    final _$menu = menu.reference;
    return _onPreparePanel(
            reference.pointer,
            _id_onPreparePanel as jni$_.JMethodIDPtr,
            i,
            _$view.pointer,
            _$menu.pointer)
        .boolean;
  }

  static final _id_onCreatePanelMenu = _class.instanceMethodId(
    r'onCreatePanelMenu',
    r'(ILandroid/view/Menu;)Z',
  );

  static final _onCreatePanelMenu = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean onCreatePanelMenu(int i, android.view.Menu menu)`
  bool onCreatePanelMenu(
    int i,
    jni$_.JObject menu,
  ) {
    final _$menu = menu.reference;
    return _onCreatePanelMenu(reference.pointer,
            _id_onCreatePanelMenu as jni$_.JMethodIDPtr, i, _$menu.pointer)
        .boolean;
  }

  static final _id_onMenuItemSelected = _class.instanceMethodId(
    r'onMenuItemSelected',
    r'(ILandroid/view/MenuItem;)Z',
  );

  static final _onMenuItemSelected = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallBooleanMethod')
      .asFunction<
          jni$_.JniResult Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public boolean onMenuItemSelected(int i, android.view.MenuItem menuItem)`
  bool onMenuItemSelected(
    int i,
    jni$_.JObject menuItem,
  ) {
    final _$menuItem = menuItem.reference;
    return _onMenuItemSelected(reference.pointer,
            _id_onMenuItemSelected as jni$_.JMethodIDPtr, i, _$menuItem.pointer)
        .boolean;
  }

  static final _id_onPanelClosed = _class.instanceMethodId(
    r'onPanelClosed',
    r'(ILandroid/view/Menu;)V',
  );

  static final _onPanelClosed = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Int32, jni$_.Pointer<jni$_.Void>)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void onPanelClosed(int i, android.view.Menu menu)`
  void onPanelClosed(
    int i,
    jni$_.JObject menu,
  ) {
    final _$menu = menu.reference;
    _onPanelClosed(reference.pointer, _id_onPanelClosed as jni$_.JMethodIDPtr,
            i, _$menu.pointer)
        .check();
  }

  static final _id_addMenuProvider = _class.instanceMethodId(
    r'addMenuProvider',
    r'(Landroidx/core/view/MenuProvider;)V',
  );

  static final _addMenuProvider = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void addMenuProvider(androidx.core.view.MenuProvider menuProvider)`
  void addMenuProvider(
    jni$_.JObject menuProvider,
  ) {
    final _$menuProvider = menuProvider.reference;
    _addMenuProvider(reference.pointer,
            _id_addMenuProvider as jni$_.JMethodIDPtr, _$menuProvider.pointer)
        .check();
  }

  static final _id_addMenuProvider$1 = _class.instanceMethodId(
    r'addMenuProvider',
    r'(Landroidx/core/view/MenuProvider;Landroidx/lifecycle/LifecycleOwner;)V',
  );

  static final _addMenuProvider$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void addMenuProvider(androidx.core.view.MenuProvider menuProvider, androidx.lifecycle.LifecycleOwner lifecycleOwner)`
  void addMenuProvider$1(
    jni$_.JObject menuProvider,
    jni$_.JObject lifecycleOwner,
  ) {
    final _$menuProvider = menuProvider.reference;
    final _$lifecycleOwner = lifecycleOwner.reference;
    _addMenuProvider$1(
            reference.pointer,
            _id_addMenuProvider$1 as jni$_.JMethodIDPtr,
            _$menuProvider.pointer,
            _$lifecycleOwner.pointer)
        .check();
  }

  static final _id_addMenuProvider$2 = _class.instanceMethodId(
    r'addMenuProvider',
    r'(Landroidx/core/view/MenuProvider;Landroidx/lifecycle/LifecycleOwner;Landroidx/lifecycle/Lifecycle$State;)V',
  );

  static final _addMenuProvider$2 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void addMenuProvider(androidx.core.view.MenuProvider menuProvider, androidx.lifecycle.LifecycleOwner lifecycleOwner, androidx.lifecycle.Lifecycle$State state)`
  void addMenuProvider$2(
    jni$_.JObject menuProvider,
    jni$_.JObject lifecycleOwner,
    jni$_.JObject state,
  ) {
    final _$menuProvider = menuProvider.reference;
    final _$lifecycleOwner = lifecycleOwner.reference;
    final _$state = state.reference;
    _addMenuProvider$2(
            reference.pointer,
            _id_addMenuProvider$2 as jni$_.JMethodIDPtr,
            _$menuProvider.pointer,
            _$lifecycleOwner.pointer,
            _$state.pointer)
        .check();
  }

  static final _id_removeMenuProvider = _class.instanceMethodId(
    r'removeMenuProvider',
    r'(Landroidx/core/view/MenuProvider;)V',
  );

  static final _removeMenuProvider = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void removeMenuProvider(androidx.core.view.MenuProvider menuProvider)`
  void removeMenuProvider(
    jni$_.JObject menuProvider,
  ) {
    final _$menuProvider = menuProvider.reference;
    _removeMenuProvider(
            reference.pointer,
            _id_removeMenuProvider as jni$_.JMethodIDPtr,
            _$menuProvider.pointer)
        .check();
  }

  static final _id_invalidateMenu = _class.instanceMethodId(
    r'invalidateMenu',
    r'()V',
  );

  static final _invalidateMenu = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void invalidateMenu()`
  void invalidateMenu() {
    _invalidateMenu(reference.pointer, _id_invalidateMenu as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_getLifecycle = _class.instanceMethodId(
    r'getLifecycle',
    r'()Landroidx/lifecycle/Lifecycle;',
  );

  static final _getLifecycle = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public androidx.lifecycle.Lifecycle getLifecycle()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getLifecycle() {
    return _getLifecycle(
            reference.pointer, _id_getLifecycle as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_getViewModelStore = _class.instanceMethodId(
    r'getViewModelStore',
    r'()Landroidx/lifecycle/ViewModelStore;',
  );

  static final _getViewModelStore = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public androidx.lifecycle.ViewModelStore getViewModelStore()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getViewModelStore() {
    return _getViewModelStore(
            reference.pointer, _id_getViewModelStore as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_getDefaultViewModelProviderFactory = _class.instanceMethodId(
    r'getDefaultViewModelProviderFactory',
    r'()Landroidx/lifecycle/ViewModelProvider$Factory;',
  );

  static final _getDefaultViewModelProviderFactory =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public androidx.lifecycle.ViewModelProvider$Factory getDefaultViewModelProviderFactory()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getDefaultViewModelProviderFactory() {
    return _getDefaultViewModelProviderFactory(reference.pointer,
            _id_getDefaultViewModelProviderFactory as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_getDefaultViewModelCreationExtras = _class.instanceMethodId(
    r'getDefaultViewModelCreationExtras',
    r'()Landroidx/lifecycle/viewmodel/CreationExtras;',
  );

  static final _getDefaultViewModelCreationExtras =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public androidx.lifecycle.viewmodel.CreationExtras getDefaultViewModelCreationExtras()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getDefaultViewModelCreationExtras() {
    return _getDefaultViewModelCreationExtras(reference.pointer,
            _id_getDefaultViewModelCreationExtras as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_onBackPressed = _class.instanceMethodId(
    r'onBackPressed',
    r'()V',
  );

  static final _onBackPressed = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void onBackPressed()`
  void onBackPressed() {
    _onBackPressed(reference.pointer, _id_onBackPressed as jni$_.JMethodIDPtr)
        .check();
  }

  static final _id_getOnBackPressedDispatcher = _class.instanceMethodId(
    r'getOnBackPressedDispatcher',
    r'()Landroidx/activity/OnBackPressedDispatcher;',
  );

  static final _getOnBackPressedDispatcher =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                    jni$_.Pointer<jni$_.Void>,
                    jni$_.JMethodIDPtr,
                  )>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>();

  /// from: `public final androidx.activity.OnBackPressedDispatcher getOnBackPressedDispatcher()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getOnBackPressedDispatcher() {
    return _getOnBackPressedDispatcher(reference.pointer,
            _id_getOnBackPressedDispatcher as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_getSavedStateRegistry = _class.instanceMethodId(
    r'getSavedStateRegistry',
    r'()Landroidx/savedstate/SavedStateRegistry;',
  );

  static final _getSavedStateRegistry = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final androidx.savedstate.SavedStateRegistry getSavedStateRegistry()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getSavedStateRegistry() {
    return _getSavedStateRegistry(
            reference.pointer, _id_getSavedStateRegistry as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_getFullyDrawnReporter = _class.instanceMethodId(
    r'getFullyDrawnReporter',
    r'()Landroidx/activity/FullyDrawnReporter;',
  );

  static final _getFullyDrawnReporter = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public androidx.activity.FullyDrawnReporter getFullyDrawnReporter()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getFullyDrawnReporter() {
    return _getFullyDrawnReporter(
            reference.pointer, _id_getFullyDrawnReporter as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_startActivityForResult = _class.instanceMethodId(
    r'startActivityForResult',
    r'(Landroid/content/Intent;I)V',
  );

  static final _startActivityForResult = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_
                          .VarArgs<(jni$_.Pointer<jni$_.Void>, jni$_.Int32)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>, int)>();

  /// from: `public void startActivityForResult(android.content.Intent intent, int i)`
  void startActivityForResult(
    intent$_.Intent intent,
    int i,
  ) {
    final _$intent = intent.reference;
    _startActivityForResult(
            reference.pointer,
            _id_startActivityForResult as jni$_.JMethodIDPtr,
            _$intent.pointer,
            i)
        .check();
  }

  static final _id_startActivityForResult$1 = _class.instanceMethodId(
    r'startActivityForResult',
    r'(Landroid/content/Intent;ILandroid/os/Bundle;)V',
  );

  static final _startActivityForResult$1 = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Int32,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              int,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void startActivityForResult(android.content.Intent intent, int i, android.os.Bundle bundle)`
  void startActivityForResult$1(
    intent$_.Intent intent,
    int i,
    jni$_.JObject? bundle,
  ) {
    final _$intent = intent.reference;
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _startActivityForResult$1(
            reference.pointer,
            _id_startActivityForResult$1 as jni$_.JMethodIDPtr,
            _$intent.pointer,
            i,
            _$bundle.pointer)
        .check();
  }

  static final _id_startIntentSenderForResult = _class.instanceMethodId(
    r'startIntentSenderForResult',
    r'(Landroid/content/IntentSender;ILandroid/content/Intent;III)V',
  );

  static final _startIntentSenderForResult =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Int32,
                            jni$_.Int32,
                            jni$_.Int32
                          )>)>>('globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.Pointer<jni$_.Void>,
                  int,
                  jni$_.Pointer<jni$_.Void>,
                  int,
                  int,
                  int)>();

  /// from: `public void startIntentSenderForResult(android.content.IntentSender intentSender, int i, android.content.Intent intent, int i1, int i2, int i3)`
  void startIntentSenderForResult(
    jni$_.JObject intentSender,
    int i,
    intent$_.Intent? intent,
    int i1,
    int i2,
    int i3,
  ) {
    final _$intentSender = intentSender.reference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    _startIntentSenderForResult(
            reference.pointer,
            _id_startIntentSenderForResult as jni$_.JMethodIDPtr,
            _$intentSender.pointer,
            i,
            _$intent.pointer,
            i1,
            i2,
            i3)
        .check();
  }

  static final _id_startIntentSenderForResult$1 = _class.instanceMethodId(
    r'startIntentSenderForResult',
    r'(Landroid/content/IntentSender;ILandroid/content/Intent;IIILandroid/os/Bundle;)V',
  );

  static final _startIntentSenderForResult$1 =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Int32,
                            jni$_.Int32,
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.Pointer<jni$_.Void>,
                  int,
                  jni$_.Pointer<jni$_.Void>,
                  int,
                  int,
                  int,
                  jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void startIntentSenderForResult(android.content.IntentSender intentSender, int i, android.content.Intent intent, int i1, int i2, int i3, android.os.Bundle bundle)`
  void startIntentSenderForResult$1(
    jni$_.JObject intentSender,
    int i,
    intent$_.Intent? intent,
    int i1,
    int i2,
    int i3,
    jni$_.JObject? bundle,
  ) {
    final _$intentSender = intentSender.reference;
    final _$intent = intent?.reference ?? jni$_.jNullReference;
    final _$bundle = bundle?.reference ?? jni$_.jNullReference;
    _startIntentSenderForResult$1(
            reference.pointer,
            _id_startIntentSenderForResult$1 as jni$_.JMethodIDPtr,
            _$intentSender.pointer,
            i,
            _$intent.pointer,
            i1,
            i2,
            i3,
            _$bundle.pointer)
        .check();
  }

  static final _id_onRequestPermissionsResult = _class.instanceMethodId(
    r'onRequestPermissionsResult',
    r'(I[Ljava/lang/String;[I)V',
  );

  static final _onRequestPermissionsResult =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  int,
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void onRequestPermissionsResult(int i, java.lang.String[] strings, int[] is)`
  void onRequestPermissionsResult(
    int i,
    jni$_.JArray<jni$_.JString?> strings,
    jni$_.JIntArray is$,
  ) {
    final _$strings = strings.reference;
    final _$is$ = is$.reference;
    _onRequestPermissionsResult(
            reference.pointer,
            _id_onRequestPermissionsResult as jni$_.JMethodIDPtr,
            i,
            _$strings.pointer,
            _$is$.pointer)
        .check();
  }

  static final _id_registerForActivityResult = _class.instanceMethodId(
    r'registerForActivityResult',
    r'(Landroidx/activity/result/contract/ActivityResultContract;Landroidx/activity/result/ActivityResultRegistry;Landroidx/activity/result/ActivityResultCallback;)Landroidx/activity/result/ActivityResultLauncher;',
  );

  static final _registerForActivityResult = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<
                      (
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>,
                        jni$_.Pointer<jni$_.Void>
                      )>)>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>,
              jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final androidx.activity.result.ActivityResultLauncher<I> registerForActivityResult(androidx.activity.result.contract.ActivityResultContract<I, O> activityResultContract, androidx.activity.result.ActivityResultRegistry activityResultRegistry, androidx.activity.result.ActivityResultCallback<O> activityResultCallback)`
  /// The returned object must be released after use, by calling the [release] method.
  activityresultlauncher$_.ActivityResultLauncher<$I?>
      registerForActivityResult<$I extends jni$_.JObject?,
          $O extends jni$_.JObject?>(
    jni$_.JObject activityResultContract,
    jni$_.JObject activityResultRegistry,
    activityresultcallback$_.ActivityResultCallback<$O?>
        activityResultCallback, {
    required jni$_.JObjType<$I> I,
    jni$_.JObjType<$O>? O,
  }) {
    O ??= jni$_.lowestCommonSuperType([
      (activityResultCallback.$type as activityresultcallback$_
              .$ActivityResultCallback$Type<core$_.dynamic>)
          .O,
    ]) as jni$_.JObjType<$O>;
    final _$activityResultContract = activityResultContract.reference;
    final _$activityResultRegistry = activityResultRegistry.reference;
    final _$activityResultCallback = activityResultCallback.reference;
    return _registerForActivityResult(
            reference.pointer,
            _id_registerForActivityResult as jni$_.JMethodIDPtr,
            _$activityResultContract.pointer,
            _$activityResultRegistry.pointer,
            _$activityResultCallback.pointer)
        .object<activityresultlauncher$_.ActivityResultLauncher<$I?>>(
            activityresultlauncher$_
                .$ActivityResultLauncher$Type<$I?>(I.nullableType));
  }

  static final _id_registerForActivityResult$1 = _class.instanceMethodId(
    r'registerForActivityResult',
    r'(Landroidx/activity/result/contract/ActivityResultContract;Landroidx/activity/result/ActivityResultCallback;)Landroidx/activity/result/ActivityResultLauncher;',
  );

  static final _registerForActivityResult$1 =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JniResult Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Pointer<jni$_.Void>,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallObjectMethod')
          .asFunction<
              jni$_.JniResult Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final androidx.activity.result.ActivityResultLauncher<I> registerForActivityResult(androidx.activity.result.contract.ActivityResultContract<I, O> activityResultContract, androidx.activity.result.ActivityResultCallback<O> activityResultCallback)`
  /// The returned object must be released after use, by calling the [release] method.
  activityresultlauncher$_.ActivityResultLauncher<$I?>
      registerForActivityResult$1<$I extends jni$_.JObject?,
          $O extends jni$_.JObject?>(
    jni$_.JObject activityResultContract,
    activityresultcallback$_.ActivityResultCallback<$O?>
        activityResultCallback, {
    required jni$_.JObjType<$I> I,
    jni$_.JObjType<$O>? O,
  }) {
    O ??= jni$_.lowestCommonSuperType([
      (activityResultCallback.$type as activityresultcallback$_
              .$ActivityResultCallback$Type<core$_.dynamic>)
          .O,
    ]) as jni$_.JObjType<$O>;
    final _$activityResultContract = activityResultContract.reference;
    final _$activityResultCallback = activityResultCallback.reference;
    return _registerForActivityResult$1(
            reference.pointer,
            _id_registerForActivityResult$1 as jni$_.JMethodIDPtr,
            _$activityResultContract.pointer,
            _$activityResultCallback.pointer)
        .object<activityresultlauncher$_.ActivityResultLauncher<$I?>>(
            activityresultlauncher$_
                .$ActivityResultLauncher$Type<$I?>(I.nullableType));
  }

  static final _id_getActivityResultRegistry = _class.instanceMethodId(
    r'getActivityResultRegistry',
    r'()Landroidx/activity/result/ActivityResultRegistry;',
  );

  static final _getActivityResultRegistry = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallObjectMethod')
      .asFunction<
          jni$_.JniResult Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public final androidx.activity.result.ActivityResultRegistry getActivityResultRegistry()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JObject getActivityResultRegistry() {
    return _getActivityResultRegistry(reference.pointer,
            _id_getActivityResultRegistry as jni$_.JMethodIDPtr)
        .object<jni$_.JObject>(const jni$_.JObjectType());
  }

  static final _id_onConfigurationChanged = _class.instanceMethodId(
    r'onConfigurationChanged',
    r'(Landroid/content/res/Configuration;)V',
  );

  static final _onConfigurationChanged = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void onConfigurationChanged(android.content.res.Configuration configuration)`
  void onConfigurationChanged(
    jni$_.JObject configuration,
  ) {
    final _$configuration = configuration.reference;
    _onConfigurationChanged(
            reference.pointer,
            _id_onConfigurationChanged as jni$_.JMethodIDPtr,
            _$configuration.pointer)
        .check();
  }

  static final _id_addOnConfigurationChangedListener = _class.instanceMethodId(
    r'addOnConfigurationChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _addOnConfigurationChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnConfigurationChangedListener(androidx.core.util.Consumer<android.content.res.Configuration> consumer)`
  void addOnConfigurationChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _addOnConfigurationChangedListener(
            reference.pointer,
            _id_addOnConfigurationChangedListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_removeOnConfigurationChangedListener =
      _class.instanceMethodId(
    r'removeOnConfigurationChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _removeOnConfigurationChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnConfigurationChangedListener(androidx.core.util.Consumer<android.content.res.Configuration> consumer)`
  void removeOnConfigurationChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _removeOnConfigurationChangedListener(
            reference.pointer,
            _id_removeOnConfigurationChangedListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_onTrimMemory = _class.instanceMethodId(
    r'onTrimMemory',
    r'(I)V',
  );

  static final _onTrimMemory = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public void onTrimMemory(int i)`
  void onTrimMemory(
    int i,
  ) {
    _onTrimMemory(reference.pointer, _id_onTrimMemory as jni$_.JMethodIDPtr, i)
        .check();
  }

  static final _id_addOnTrimMemoryListener = _class.instanceMethodId(
    r'addOnTrimMemoryListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _addOnTrimMemoryListener = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnTrimMemoryListener(androidx.core.util.Consumer<java.lang.Integer> consumer)`
  void addOnTrimMemoryListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _addOnTrimMemoryListener(
            reference.pointer,
            _id_addOnTrimMemoryListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_removeOnTrimMemoryListener = _class.instanceMethodId(
    r'removeOnTrimMemoryListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _removeOnTrimMemoryListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnTrimMemoryListener(androidx.core.util.Consumer<java.lang.Integer> consumer)`
  void removeOnTrimMemoryListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _removeOnTrimMemoryListener(
            reference.pointer,
            _id_removeOnTrimMemoryListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_addOnNewIntentListener = _class.instanceMethodId(
    r'addOnNewIntentListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _addOnNewIntentListener = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnNewIntentListener(androidx.core.util.Consumer<android.content.Intent> consumer)`
  void addOnNewIntentListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _addOnNewIntentListener(
            reference.pointer,
            _id_addOnNewIntentListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_removeOnNewIntentListener = _class.instanceMethodId(
    r'removeOnNewIntentListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _removeOnNewIntentListener = jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
          'globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnNewIntentListener(androidx.core.util.Consumer<android.content.Intent> consumer)`
  void removeOnNewIntentListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _removeOnNewIntentListener(
            reference.pointer,
            _id_removeOnNewIntentListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_onMultiWindowModeChanged = _class.instanceMethodId(
    r'onMultiWindowModeChanged',
    r'(Z)V',
  );

  static final _onMultiWindowModeChanged = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr,
                  jni$_.VarArgs<(jni$_.Int32,)>)>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public void onMultiWindowModeChanged(boolean z)`
  void onMultiWindowModeChanged(
    bool z,
  ) {
    _onMultiWindowModeChanged(reference.pointer,
            _id_onMultiWindowModeChanged as jni$_.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_onMultiWindowModeChanged$1 = _class.instanceMethodId(
    r'onMultiWindowModeChanged',
    r'(ZLandroid/content/res/Configuration;)V',
  );

  static final _onMultiWindowModeChanged$1 =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void onMultiWindowModeChanged(boolean z, android.content.res.Configuration configuration)`
  void onMultiWindowModeChanged$1(
    bool z,
    jni$_.JObject configuration,
  ) {
    final _$configuration = configuration.reference;
    _onMultiWindowModeChanged$1(
            reference.pointer,
            _id_onMultiWindowModeChanged$1 as jni$_.JMethodIDPtr,
            z ? 1 : 0,
            _$configuration.pointer)
        .check();
  }

  static final _id_addOnMultiWindowModeChangedListener =
      _class.instanceMethodId(
    r'addOnMultiWindowModeChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _addOnMultiWindowModeChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnMultiWindowModeChangedListener(androidx.core.util.Consumer<androidx.core.app.MultiWindowModeChangedInfo> consumer)`
  void addOnMultiWindowModeChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _addOnMultiWindowModeChangedListener(
            reference.pointer,
            _id_addOnMultiWindowModeChangedListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_removeOnMultiWindowModeChangedListener =
      _class.instanceMethodId(
    r'removeOnMultiWindowModeChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _removeOnMultiWindowModeChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnMultiWindowModeChangedListener(androidx.core.util.Consumer<androidx.core.app.MultiWindowModeChangedInfo> consumer)`
  void removeOnMultiWindowModeChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _removeOnMultiWindowModeChangedListener(
            reference.pointer,
            _id_removeOnMultiWindowModeChangedListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_onPictureInPictureModeChanged = _class.instanceMethodId(
    r'onPictureInPictureModeChanged',
    r'(Z)V',
  );

  static final _onPictureInPictureModeChanged =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr, jni$_.VarArgs<(jni$_.Int32,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(
                  jni$_.Pointer<jni$_.Void>, jni$_.JMethodIDPtr, int)>();

  /// from: `public void onPictureInPictureModeChanged(boolean z)`
  void onPictureInPictureModeChanged(
    bool z,
  ) {
    _onPictureInPictureModeChanged(reference.pointer,
            _id_onPictureInPictureModeChanged as jni$_.JMethodIDPtr, z ? 1 : 0)
        .check();
  }

  static final _id_onPictureInPictureModeChanged$1 = _class.instanceMethodId(
    r'onPictureInPictureModeChanged',
    r'(ZLandroid/content/res/Configuration;)V',
  );

  static final _onPictureInPictureModeChanged$1 =
      jni$_.ProtectedJniExtensions.lookup<
              jni$_.NativeFunction<
                  jni$_.JThrowablePtr Function(
                      jni$_.Pointer<jni$_.Void>,
                      jni$_.JMethodIDPtr,
                      jni$_.VarArgs<
                          (
                            jni$_.Int32,
                            jni$_.Pointer<jni$_.Void>
                          )>)>>('globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, int, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public void onPictureInPictureModeChanged(boolean z, android.content.res.Configuration configuration)`
  void onPictureInPictureModeChanged$1(
    bool z,
    jni$_.JObject configuration,
  ) {
    final _$configuration = configuration.reference;
    _onPictureInPictureModeChanged$1(
            reference.pointer,
            _id_onPictureInPictureModeChanged$1 as jni$_.JMethodIDPtr,
            z ? 1 : 0,
            _$configuration.pointer)
        .check();
  }

  static final _id_addOnPictureInPictureModeChangedListener =
      _class.instanceMethodId(
    r'addOnPictureInPictureModeChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _addOnPictureInPictureModeChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void addOnPictureInPictureModeChangedListener(androidx.core.util.Consumer<androidx.core.app.PictureInPictureModeChangedInfo> consumer)`
  void addOnPictureInPictureModeChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _addOnPictureInPictureModeChangedListener(
            reference.pointer,
            _id_addOnPictureInPictureModeChangedListener as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_removeOnPictureInPictureModeChangedListener =
      _class.instanceMethodId(
    r'removeOnPictureInPictureModeChangedListener',
    r'(Landroidx/core/util/Consumer;)V',
  );

  static final _removeOnPictureInPictureModeChangedListener =
      jni$_.ProtectedJniExtensions.lookup<
                  jni$_.NativeFunction<
                      jni$_.JThrowablePtr Function(
                          jni$_.Pointer<jni$_.Void>,
                          jni$_.JMethodIDPtr,
                          jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>)>>(
              'globalEnv_CallVoidMethod')
          .asFunction<
              jni$_.JThrowablePtr Function(jni$_.Pointer<jni$_.Void>,
                  jni$_.JMethodIDPtr, jni$_.Pointer<jni$_.Void>)>();

  /// from: `public final void removeOnPictureInPictureModeChangedListener(androidx.core.util.Consumer<androidx.core.app.PictureInPictureModeChangedInfo> consumer)`
  void removeOnPictureInPictureModeChangedListener(
    jni$_.JObject consumer,
  ) {
    final _$consumer = consumer.reference;
    _removeOnPictureInPictureModeChangedListener(
            reference.pointer,
            _id_removeOnPictureInPictureModeChangedListener
                as jni$_.JMethodIDPtr,
            _$consumer.pointer)
        .check();
  }

  static final _id_reportFullyDrawn = _class.instanceMethodId(
    r'reportFullyDrawn',
    r'()V',
  );

  static final _reportFullyDrawn = jni$_.ProtectedJniExtensions.lookup<
          jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )>>('globalEnv_CallVoidMethod')
      .asFunction<
          jni$_.JThrowablePtr Function(
            jni$_.Pointer<jni$_.Void>,
            jni$_.JMethodIDPtr,
          )>();

  /// from: `public void reportFullyDrawn()`
  void reportFullyDrawn() {
    _reportFullyDrawn(
            reference.pointer, _id_reportFullyDrawn as jni$_.JMethodIDPtr)
        .check();
  }
}

final class $ComponentActivity$NullableType
    extends jni$_.JObjType<ComponentActivity?> {
  @jni$_.internal
  const $ComponentActivity$NullableType();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroidx/activity/ComponentActivity;';

  @jni$_.internal
  @core$_.override
  ComponentActivity? fromReference(jni$_.JReference reference) =>
      reference.isNull
          ? null
          : ComponentActivity.fromReference(
              reference,
            );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ComponentActivity?> get nullableType => this;

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ComponentActivity$NullableType).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ComponentActivity$NullableType) &&
        other is $ComponentActivity$NullableType;
  }
}

final class $ComponentActivity$Type extends jni$_.JObjType<ComponentActivity> {
  @jni$_.internal
  const $ComponentActivity$Type();

  @jni$_.internal
  @core$_.override
  String get signature => r'Landroidx/activity/ComponentActivity;';

  @jni$_.internal
  @core$_.override
  ComponentActivity fromReference(jni$_.JReference reference) =>
      ComponentActivity.fromReference(
        reference,
      );
  @jni$_.internal
  @core$_.override
  jni$_.JObjType get superType => const jni$_.JObjectNullableType();

  @jni$_.internal
  @core$_.override
  jni$_.JObjType<ComponentActivity?> get nullableType =>
      const $ComponentActivity$NullableType();

  @jni$_.internal
  @core$_.override
  final superCount = 1;

  @core$_.override
  int get hashCode => ($ComponentActivity$Type).hashCode;

  @core$_.override
  bool operator ==(Object other) {
    return other.runtimeType == ($ComponentActivity$Type) &&
        other is $ComponentActivity$Type;
  }
}
